[[inputs.mqtt_consumer]]
  servers = ["tcp://hivemq:1883"]
  topics = [
    "iot/energy/meter/demo",
    "iot/heat/meter/demo"
  ]
  data_format = "json"
  name_override = "iot_meters"
  tag_keys = ["device_id", "meter_type"]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "super-secret-token"
  organization = "iot"
  bucket = "energy"
